name: API Automation Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging

      suite:
        description: 'Test suite'
        required: true
        default: 'smoke-suite.xml'
        type: choice
        options:
          - user-suite.xml
          - smoke-suite.xml
          - regression-suite.xml

  schedule:
    - cron: '0 19 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://dummyjson.com
      ENABLE_LOG: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run API tests
        run: |
          mvn clean test \
          -Denv=${{ github.event.inputs.environment || 'staging' }} \
          -DsuiteXmlFile=src/test/resources/suites/${{ github.event.inputs.suite || 'smoke-suite.xml' }}

      - name: Generate Allure Report
        run: |
          mvn allure:report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: reports/

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          publish_branch: gh-pages