name: API Automation Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging

      suite:
        description: 'Test suite'
        required: true
        default: 'smoke.xml'
        type: choice
        options:
          - user-suite.xml
          - smoke.xml
          - regression.xml

  schedule:
    # 2:00 AM Vietnam = 19:00 UTC
    - cron: '0 19 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://dummyjson.com
      ENABLE_LOG: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run API tests (when commiting code)
        run: |
          mvn clean test \
          -Denv=${{ github.event.inputs.environment || 'staging' }} \
          -DsuiteXmlFile=src/test/resources/suites/${{ github.event.inputs.suite || 'smoke.xml' }}

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: reports/